services:
  postgres:
    image: postgres:16-alpine
    container_name: pg-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  data-api:
    build:
      context: ./data-api
      dockerfile: Dockerfile
    container_name: data-api
    environment:
      INTERNAL_TOKEN: ${INTERNAL_TOKEN}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: unless-stopped

  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    container_name: auth-api
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/authdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      INTERNAL_TOKEN: ${INTERNAL_TOKEN}
      DATA_API_BASE_URL: http://data-api:8081
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - data-api
    restart: on-failure

volumes:
  pgdata:
